### ISSUE TITLE
File Assets Error: The bucket is in this region: 

### ISSUE THREAD

**Issue by johanbjorn** [cdklabs/cdk-stacksets#159]
With the following code: 

`
    app = App()
    
    stack1 = Stack(
        app,
        "MyStackThu28jun611",
        env=Environment(region="eu-central-1", account="088713361256"),
    )

    bucket = Bucket(
        stack1,
        "Assets",
        bucket_name="cdkstacket-asset-bucket-28jun6",
        removal_policy=RemovalPolicy.DESTROY,
    )
    bucket.add_to_resource_policy(
        PolicyStatement(
            actions=["s3:Get*", "s3:List*"],
            resources=[bucket.arn_for_objects("*"), bucket.bucket_arn],
            principals=[OrganizationPrincipal("o-xxxxx")],
        )
    )
    for i in range(1, 3):
        stack = Stack(
            app,
            f"MyStackThu28jun6{i}",
        )
        devcontainer2_stack = Devcontainer(
            stack, f"Devcontainer2Stack2Thu28Jun1{i}", asset_bucket=bucket
        )
        StackSet(
            stack,
            f"StackSet2Thu28Jun{i}",
            capabilities=[Capability.NAMED_IAM],
            target=StackSetTarget.from_organizational_units(
                regions=["eu-central-1", "eu-west-1"],
                organizational_units=["r-nXXn"],
            ),
            deployment_type=DeploymentType.service_managed(),
            template=StackSetTemplate.from_stack_set_stack(devcontainer2_stack),
            operation_preferences=OperationPreferences(
                region_concurrency_type=RegionConcurrencyType.PARALLEL,
                max_concurrent_percentage=100,
                failure_tolerance_percentage=99,
            ),
        )
    app.synth()`

I get this error
"Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: eu-central-1. Please use this region to retry the request "

If I remove "eu-west-1" from deploy_regions I don't get this error and deployment is successful.

**Comment by corymhall** [comment]
@josh-demuth

**Comment by josh-demuth** [comment]
thank you for reporting this. we are working on a fix

**Comment by DaniDipp** [comment]
In the meantime, is there a workaround for this other than creating a separate single-region StackSet for each region?

**Comment by josh-demuth** [comment]
unfortunately that is the guidance at this point where you would have a single stackset per region. thanks for your patience on the fix. this is prioritized and my goal is to have something up soon.

**Comment by juho9000** [comment]
What do you think about the approach taken [here](https://github.com/pgarbe/cdk-stackset)?

**Comment by juho9000** [comment]
@josh-demuth Any news?

**Comment by josh-demuth** [comment]
thanks for your patience. PR just opened. what Philipp did was in line with what we were discussing as well.
