### ISSUE TITLE
when calling the PutObject operation: Access Denied 

### ISSUE THREAD

**Issue by Mark-CloudNation** [cdklabs/cdk-stacksets#428]
During the deployment I get the error:
[ERROR]	2024-04-24T14:04:06.667Z	81f98692-5895-4c01-a0f9-c3c45a730c9c	Command '['/opt/awscli/aws', 's3', 'sync', '/tmp/tmpwkkbiffp/contents', 's3://cdkstackset-asset-bucket-xxx-xxx-xxx-xxxx/']' returned non-zero exit status 1.

And discovered that asset bucket deployment custom resource, doesn't get permissions to the destination S3 bucket:

<img width="557" alt="Screenshot 2024-04-26 at 13 04 50" src="https://github.com/cdklabs/cdk-stacksets/assets/77144921/d61358f5-0c0f-4af1-b966-6662bb92fd0c">
<img width="779" alt="Screenshot 2024-04-26 at 13 04 42" src="https://github.com/cdklabs/cdk-stacksets/assets/77144921/a874f3b5-88b1-4563-8626-d77307b6e076">
<img width="703" alt="Screenshot 2024-04-26 at 13 04 20" src="https://github.com/cdklabs/cdk-stacksets/assets/77144921/4cacd492-677b-45f2-bc96-ef2070a4f46a">
<img width="627" alt="Screenshot 2024-04-26 at 13 07 21" src="https://github.com/cdklabs/cdk-stacksets/assets/77144921/d5b045c3-3fbd-4ef3-9ce1-866ce08b04ef">

**Comment by Mark-CloudNation** [comment]
Found the issue.

**Comment by kaidobit** [comment]
> Found the issue.

are you gonna ellaborate?
