### ISSUE TITLE
(stacksets)feat: Add support for Assets for stacksets construct

### ISSUE THREAD

**Issue by evgenyka** [cdklabs/cdk-stacksets#58]
Currently Assets are not supported by stackset construct, see https://github.com/cdklabs/cdk-stacksets/
The ask is for adding support for assets there.

**Comment by kabo** [comment]
This has been solved for service catalog products. Perhaps something similar can be done here?
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_servicecatalog-readme.html#using-assets-in-your-product-stack
